//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HTMLToQPDF.Example.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HTMLToQPDF.Example.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;reader-container container container_center&quot;&gt;
        ///    &lt;div class=&quot;article-image&quot;&gt;
        ///        &lt;a href=&quot;https://github.com/&quot;&gt;
        ///            &lt;img class=&quot;lazyload&quot;
        ///                 data-background=&quot;&quot;
        ///                 src=&quot;shortTestImage.png&quot; /&gt;
        ///        &lt;/a&gt;
        ///    &lt;/div&gt;
        ///    &lt;p&gt;Lorem&lt;/p&gt;
        ///    &lt;h1&gt;h1&lt;/h1&gt;
        ///    &lt;h2&gt;&lt;s&gt;h2&lt;/s&gt;&lt;/h2&gt;
        ///    &lt;h3&gt;h3&lt;/h3&gt;
        ///    &lt;h4&gt;h4&lt;/h4&gt;
        ///    &lt;h5&gt;h5&lt;/h5&gt;
        ///    &lt;br /&gt;
        ///    &lt;br /&gt;
        ///    &lt;br /&gt;
        ///    &lt;br /&gt;
        ///    &lt;h6&gt;h6&lt;/h6&gt;
        ///    &lt;p&gt;
        ///        &lt;s&gt;Lorem &amp;nbsp;&amp;nbsp;ipsum&lt;/s&gt; dolor &lt;br /&gt;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string testHtml {
            get {
                return ResourceManager.GetString("testHtml", resourceCulture);
            }
        }
    }
}
